### ISSUE TITLE
Problem installing module

### ISSUE THREAD

**Issue by xael-fry** [playframework/play1#1126]
Report from [playframework #7101](https://github.com/playframework/playframework/issues/7101#issuecomment-287559208)

Play Version (1.3x/1.4x)
Operating System (Centos; RHEL6.6/6.8)
Expected Behavior

    ./play install spring-1.0.3
    Expected to install the spring module

Actual Behavior

    ./play install spring-1.0.3
    Receive the following:
    Cannot fetch the modules list from http://www.playframework.com/modules (403)...
    If the link is changed from http to https (DEFAULT_REPO = 'https://www.playframework.com') in ./framework/pym/play/commands/modulesrepo.py, the following is observed:
    Cannot fetch the modules list from https://www.playframework.com/modules ...

Did something change about how the supporting modules are retrieved?

**Comment by gjesse** [comment]
I am also experiencing this attempting to install mockito module.

**Comment by eltmon** [comment]
+1 For elasticsearch module

**Comment by xael-fry** [comment]
Problem should be for all modules, I have an error ```Downloading HTTPS pages with urllib, error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error```

**Comment by xabolcs** [comment]
Will be the fix backported for 1.2.x, 1.3.x and 1.4.x too?

**Comment by xael-fry** [comment]
@xabolcs  only 1.4.x and 1.5.x version will be updated

**Comment by xabolcs** [comment]
Thanks!

**Comment by fdenesreply** [comment]
hi @xael-fry, do you have any planned release date for 1.4.x?

**Comment by xael-fry** [comment]
@fdenesreply I just merged the fix so I will release should be available next week.
Thank

**Comment by flybyray** [comment]
please do not release this, there are several libs missing, which are referenced.
For example where is unittest ?

https://github.com/playframework/play1/blob/9ac15f7d17ef96175dcc3dfcd305312576ca853b/samples-and-tests/i-am-a-developer/tests.py#L3

**Comment by fdenesreply** [comment]
hi @xael-fry, after building play from latest sources I'm still getting the same error
`
$play install oauth-1.0
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.5.x-5e564b5, https://www.playframework.com
~
~ Oops,
~ Cannot fetch the modules list from https://www.playframework.com/modules ...
~
`

**Comment by mgrulich** [comment]
Hi @xael-fry,

is there any plan to release the fix?

Best regards

**Comment by fdenesreply** [comment]
Hi @xael-fry,

any update in this issue? You marked it as closed, but building play from sources I'm still getting the same error. 

Best regards

**Comment by xael-fry** [comment]
@fdenesreply I just try to install  `play install oauth-1.0` it is working perfectly.
On which OS did ou run it?

**Comment by fdenesreply** [comment]
@xael-fry I'm still getting the error. Mac OS (latest version). Python 2.7.10.

**Comment by xael-fry** [comment]
@fdenesreply with the same console message?

**Comment by fdenesreply** [comment]
@xael-fry yes
Cannot fetch the modules list from https://www.playframework.com/modules ...
